# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_authorization(object):
    def setupUi(self, authorization):
        authorization.setObjectName("authorization")
        authorization.resize(529, 553)
        authorization.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(authorization)
        self.centralwidget.setStyleSheet("QWidget{\n"
"background-color: white\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.login = QtWidgets.QLineEdit(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(180, 190, 171, 31))
        self.login.setStyleSheet("QLineEdit{\n"
"border: 1px solid rgb(188, 188, 186);\n"
"border-radius: 10px;\n"
"}")
        self.login.setText("")
        self.login.setObjectName("login")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(180, 260, 171, 31))
        self.password.setStyleSheet("QLineEdit{\n"
"border: 1px solid rgb(188, 188, 186);\n"
"border-radius: 10px;\n"
"}")
        self.password.setObjectName("password")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(200, 330, 121, 41))
        self.pushButton.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"border: 1px solid rgb(188, 188, 186);\n"
"border-radius: 10px;\n"
"background-color: rgb(219, 255, 246)\n"
"}")
        self.pushButton.setCheckable(False)
        self.pushButton.setAutoRepeatDelay(300)
        self.pushButton.setObjectName("pushButton")
        self.password.raise_()
        self.pushButton.raise_()
        self.login.raise_()
        authorization.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(authorization)
        self.statusbar.setObjectName("statusbar")
        authorization.setStatusBar(self.statusbar)

        self.retranslateUi(authorization)
        QtCore.QMetaObject.connectSlotsByName(authorization)

    def retranslateUi(self, authorization):
        _translate = QtCore.QCoreApplication.translate
        authorization.setWindowTitle(_translate("authorization", "MainWindow"))
        self.login.setPlaceholderText(_translate("authorization", "Логин"))
        self.password.setPlaceholderText(_translate("authorization", "Пароль"))
        self.pushButton.setText(_translate("authorization", "ВОЙТИ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    authorization = QtWidgets.QMainWindow()
    ui = Ui_authorization()
    ui.setupUi(authorization)
    authorization.show()
    sys.exit(app.exec_())
