# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_admin_sign_in(object):
    def setupUi(self, admin_sign_in):
        admin_sign_in.setObjectName("admin_sign_in")
        admin_sign_in.resize(521, 408)
        self.centralwidget = QtWidgets.QWidget(admin_sign_in)
        self.centralwidget.setObjectName("centralwidget")
        self.login_admin = QtWidgets.QLineEdit(self.centralwidget)
        self.login_admin.setGeometry(QtCore.QRect(170, 130, 181, 31))
        self.login_admin.setStyleSheet("QLineEdit{\n"
                                       "border: 1px solid rgb(188, 188, 186);\n"
                                       "border-radius: 10px;\n"
                                       "}")
        self.login_admin.setText("")
        self.login_admin.setObjectName("login_admin")
        self.password_admin = QtWidgets.QLineEdit(self.centralwidget)
        self.password_admin.setGeometry(QtCore.QRect(170, 200, 181, 31))
        self.password_admin.setStyleSheet("QLineEdit{\n"
                                          "border: 1px solid rgb(188, 188, 186);\n"
                                          "border-radius: 10px;\n"
                                          "}")
        self.password_admin.setObjectName("password_admin")
        self.sign_in_admin = QtWidgets.QPushButton(self.centralwidget)
        self.sign_in_admin.setGeometry(QtCore.QRect(270, 260, 81, 31))
        self.sign_in_admin.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(10)
        self.sign_in_admin.setFont(font)
        self.sign_in_admin.setStyleSheet("QPushButton{\n"
                                         "border: 1px solid rgb(188, 188, 186);\n"
                                         "border-radius: 10px;\n"
                                         "background-color: rgb(219, 255, 246)\n"
                                         "}")
        self.sign_in_admin.setCheckable(False)
        self.sign_in_admin.setAutoRepeatDelay(300)
        self.sign_in_admin.setObjectName("sign_in_admin")
        self.cancel_admin = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_admin.setGeometry(QtCore.QRect(170, 260, 81, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(10)
        self.cancel_admin.setFont(font)
        self.cancel_admin.setStyleSheet("QPushButton{\n"
                                        "border: 1px solid rgb(188, 188, 186);\n"
                                        "border-radius: 10px;\n"
                                        "background-color: rgb(183, 196, 255)\n"
                                        "}\n"
                                        "")
        self.cancel_admin.setObjectName("cancel_admin")
        admin_sign_in.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(admin_sign_in)
        self.statusbar.setObjectName("statusbar")
        admin_sign_in.setStatusBar(self.statusbar)

        self.retranslateUi(admin_sign_in)
        QtCore.QMetaObject.connectSlotsByName(admin_sign_in)

    def retranslateUi(self, admin_sign_in):
        _translate = QtCore.QCoreApplication.translate
        admin_sign_in.setWindowTitle(_translate("admin_sign_in", "Admin"))
        self.login_admin.setPlaceholderText(_translate("admin_sign_in", "Login.."))
        self.password_admin.setPlaceholderText(_translate("admin_sign_in", "Password.."))
        self.sign_in_admin.setText(_translate("admin_sign_in", "Sign in"))
        self.cancel_admin.setText(_translate("admin_sign_in", "Cancel"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    admin_sign_in = QtWidgets.QMainWindow()
    ui = Ui_admin_sign_in()
    ui.setupUi(admin_sign_in)
    admin_sign_in.show()
    sys.exit(app.exec_())
