# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_registration(object):
    def setupUi(self, registration):
        registration.setObjectName("registration")
        registration.resize(391, 423)
        self.centralwidget = QtWidgets.QWidget(registration)
        self.centralwidget.setObjectName("centralwidget")
        self.login_label = QtWidgets.QLabel(self.centralwidget)
        self.login_label.setGeometry(QtCore.QRect(100, 130, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.login_label.setFont(font)
        self.login_label.setObjectName("login_label")
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(68, 180, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.confirm_label = QtWidgets.QLabel(self.centralwidget)
        self.confirm_label.setGeometry(QtCore.QRect(82, 230, 65, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.confirm_label.setFont(font)
        self.confirm_label.setObjectName("confirm_label")
        self.login_regist = QtWidgets.QLineEdit(self.centralwidget)
        self.login_regist.setGeometry(QtCore.QRect(160, 125, 141, 29))
        self.login_regist.setStyleSheet("QLineEdit{\n"
                                        "border: 1px solid rgb(188, 188, 186);\n"
                                        "border-radius: 10px;\n"
                                        "}")
        self.login_regist.setObjectName("login_regist")
        self.password_regist = QtWidgets.QLineEdit(self.centralwidget)
        self.password_regist.setGeometry(QtCore.QRect(160, 175, 141, 29))
        self.password_regist.setStyleSheet("QLineEdit{\n"
                                           "border: 1px solid rgb(188, 188, 186);\n"
                                           "border-radius: 10px;\n"
                                           "}")
        self.password_regist.setObjectName("password_regist")
        self.confirm_regist = QtWidgets.QLineEdit(self.centralwidget)
        self.confirm_regist.setGeometry(QtCore.QRect(160, 225, 141, 29))
        self.confirm_regist.setStyleSheet("QLineEdit{\n"
                                          "border: 1px solid rgb(188, 188, 186);\n"
                                          "border-radius: 10px;\n"
                                          "}")
        self.confirm_regist.setObjectName("confirm_regist")
        self.send_reg_form = QtWidgets.QPushButton(self.centralwidget)
        self.send_reg_form.setGeometry(QtCore.QRect(200, 290, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(10)
        self.send_reg_form.setFont(font)
        self.send_reg_form.setStyleSheet("QPushButton{\n"
                                         "border: 1px solid rgb(188, 188, 186);\n"
                                         "border-radius: 10px;\n"
                                         "background-color: rgb(219, 255, 246)\n"
                                         "}\n"
                                         "")
        self.send_reg_form.setObjectName("send_reg_form")
        self.cancel_reg = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_reg.setGeometry(QtCore.QRect(70, 290, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(10)
        self.cancel_reg.setFont(font)
        self.cancel_reg.setStyleSheet("QPushButton{\n"
                                      "border: 1px solid rgb(188, 188, 186);\n"
                                      "border-radius: 10px;\n"
                                      "background-color: rgb(183, 196, 255)\n"
                                      "}\n"
                                      "")
        self.cancel_reg.setObjectName("cancel_reg")
        registration.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(registration)
        self.statusbar.setObjectName("statusbar")
        registration.setStatusBar(self.statusbar)

        self.retranslateUi(registration)
        QtCore.QMetaObject.connectSlotsByName(registration)

    def retranslateUi(self, registration):
        _translate = QtCore.QCoreApplication.translate
        registration.setWindowTitle(_translate("registration", "Sign up"))
        self.login_label.setText(_translate("registration", "Login:"))
        self.password_label.setText(_translate("registration", "Password:"))
        self.confirm_label.setText(_translate("registration", "Confirm: "))
        self.send_reg_form.setText(_translate("registration", "Send"))
        self.cancel_reg.setText(_translate("registration", "Cancel"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    registration = QtWidgets.QMainWindow()
    ui = Ui_registration()
    ui.setupUi(registration)
    registration.show()
    sys.exit(app.exec_())
